### ISSUE TITLE
[BUG]: `MilvusRetrieverConfig` has `vector_field` property, but `MilvusRetriever` expects `vector_field_name`, so you cannot actually set the vector field

### ISSUE THREAD

**Issue by BrianMcBrayer** [NVIDIA/AgentIQ#121]
### Version

develop branch

### Which installation method(s) does this occur on?

Source

### Describe the bug.

I would expect this to set the vector field of my milvus database:
```
retrievers:
  nvidia_retriever:
    _type: milvus_retriever
    uri: http://<some_ip>/
    connection_args:
      db_name: milvus
    collection_name: milvus
    embedding_model: milvus_embedder
    top_k: 10
    vector_field: embedding
```

But the vector field is always the default "vector".

When I look at the source, I see that the MilvusRetrieverConfig wants a `vector_field` property:
https://github.com/NVIDIA/AgentIQ/blob/e0812ba5120327e0cf14df54622e6432683a6e8e/src/aiq/retriever/milvus/register.py#L47

and passes that along to the MilvusRetriever:
https://github.com/NVIDIA/AgentIQ/blob/e0812ba5120327e0cf14df54622e6432683a6e8e/src/aiq/retriever/milvus/register.py#L75

But the MilvusRetriever, after going through `bind` and `_search_func`, expects an argument named `vector_field_name`, which doesn't match the provided argument `vector_field`.
https://github.com/NVIDIA/AgentIQ/blob/e0812ba5120327e0cf14df54622e6432683a6e8e/src/aiq/retriever/milvus/retriever.py#L90

The matching test only tests that the properties are set to their defaults, so they would not cover this case.

AgentIQ is fantastic, by the way.

### Minimum reproducible example

```shell
retrievers:
  nvidia_retriever:
    _type: milvus_retriever
    uri: http://<some_ip>/
    connection_args:
      db_name: milvus
    collection_name: milvus
    embedding_model: milvus_embedder
    top_k: 10
    vector_field: embedding


When run, the `vector_field` is still set to "vector"
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [x] I agree to follow AgentIQ' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/NVIDIA/AgentIQ/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report
