### ISSUE TITLE
Provide an example for using local llm in config

### ISSUE THREAD

**Issue by briancaffey** [NVIDIA/AgentIQ#34]
I'm trying to use a locally running OpenAI API-compatible LLM (using vLLM running locally in a docker container). Is this supported, or is there only support for using the official openai API with an OpenAI API key? If using a local LLM is supported, what should be used in the configuration?

Here's the config I am trying to use:

```
llms:
  local_llm:
    _type: openai
    api_base: "http://192.168.5.173:8000/v1"
    model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
    temperature: 0.7
    max_tokens: 1024
    api_key: "sk-abc123"
```

I'm running my local LLM with this command:

```
docker run \
  --runtime nvidia \
  --gpus all \
  -v ~/.cache/huggingface:/root/.cache/huggingface \
  --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
  -p 8000:8000 \
  --ipc=host \
  vllm/vllm-openai:latest \
  --api-key sk-abc123 \
  --model deepseek-ai/DeepSeek-R1-Distill-Qwen-7B \
  --gpu-memory-utilization 0.95 \
  --max-model-len 65536
```

Here's the error I'm getting:

```
(.venv) brian@a2:~/git/agentiq$ aiq run --config_file=config.yml --input "What is the capital of France?"
...
Workflow Result:
["Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-abc123. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"]
```

**Comment by reikote** [comment]
vLLM is probably not supported at this time, so you should use DeepSeek of NIM. I haven't tried DeepSeek, but other local NIMs are working well.

```
functions:
   # Add a tool to search wikipedia
   wikipedia_search:
      _type: wiki_search
      max_results: 2

llms:
   # Tell AgentIQ which LLM to use for the agent
   nim_llm:
      _type: nim
      model_name: meta/llama-3.1-70b-instruct
      base_url: http://xxxxxxxxxxxx/v1
      temperature: 0.0
      

workflow:
   # Use an agent that 'reasons' and 'acts'
   _type: react_agent
   # Give it access to our wikipedia search tool
   tool_names: [wikipedia_search]
   # Tell it which LLM to use
   llm_name: nim_llm
   # Make it verbose
   verbose: true
   # Retry parsing errors because LLMs are non-deterministic
   retry_parsing_errors: true
   # Retry up to 3 times
   max_retries: 3
```

One concern is that DeepSeek does not seem to support 'tool calling'. That mens DeepSeek might not be usable from AI Agents.
(https://docs.nvidia.com/nim/large-language-models/latest/models.html#models)

**Comment by dagardner-nv** [comment]
@briancaffey I was able to get this working. I think the key thing you're missing is that the config entry should be `base_url` not `api_base`.

I took the `examples/simple/configs/config.yml` config, and swapped out the `llms` section giving me:
```yaml
functions:
  webpage_query:
    _type: webpage_query
    webpage_url: https://docs.smith.langchain.com/user_guide
    description: "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!"
    embedder_name: nv-embedqa-e5-v5
    chunk_size: 512
  current_datetime:
    _type: current_datetime

llms:
  nim_llm:
    _type: openai
    base_url: "http://localhost:8000/v1"
    model_name: Qwen/Qwen2.5-1.5B-Instruct
    temperature: 0.0

embedders:
  nv-embedqa-e5-v5:
    _type: nim
    model_name: nvidia/nv-embedqa-e5-v5

workflow:
  _type: react_agent
  tool_names: [webpage_query, current_datetime]
  llm_name: nim_llm
  verbose: true
  retry_parsing_errors: true
  max_retries: 3
```

I'm using the `Qwen/Qwen2.5-1.5B-Instruct` here just because that's what's used in the vLLM quickstart. I tested it with:
```bash
aiq run --config_file .tmp/issue_34.yml --input "San Francisco is a"
```
