### ISSUE TITLE
[FEA]: Provide an output customizer

### ISSUE THREAD

**Issue by AnuradhaKaruppiah** [NVIDIA/AgentIQ#66]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem this feature solves

Provide a way to adapt the profiler output provided by evaluation -
1. I would like to include a script in the config file that is run at the end of evaluation
2. The script uses the output_dir as "input" and generate new files (that are stored in the output_dir).

### Describe your ideal solution

```
eval:
  general:
    output: # output config overrides output_dir
      custom_script:
        - script: examples/simple/src/aiq_simple/scripts/post_process.py
          args:
            - ./.tmp/aiq/examples/simple/
 ```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I have searched the [open feature requests](https://github.com/NVIDIA/AgentIQ/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request
